---
title: "Robust"
output: pdf_document
date: "2025-11-25"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(MASS)
library(tidyverse)
library(quantreg)
library(car)
library(this.path)
library(Metrics)
setwd(this.path::here())
```

Read data and subset to columns used for RLM

```{r}
df <-  read.csv("full_data_ohare_2024_v2.csv")
data <- df[,c("arr_delay", "prcp", "snow", "awnd", "tmax", "distance", "crs_dep_time_base10")]
data <- drop_na(data)
```

Define unsupplied psis

```{r}
# least squares loss
psi.ls <- function(u, deriv = 0) {
  n = length(u)
  return(rep(1, n))
}

# Andrews' Sine
psi.andrew <- function(u, c = 1.339, deriv = 0) {
  t = u/c
  if (!deriv) {
    return(ifelse(abs(u)<=pi*c, sin(t)/u, 0))
  }
  return(ifelse(abs(u)<=pi*c, cos(t)/c, 0))
}
```


Choose which M-estimators to use

```{r}
M.estimators <- c(
  least.square = psi.ls,
  least.abs.dev = NA,
  huber = psi.huber,
  tukey = psi.bisquare,
  andrews = psi.andrew
)
```

Perform robust regression with outliers present

```{r}
MADs <- numeric()
MSEs <- numeric()
for (M.estimator in names(M.estimators)) {
  M.phi <- M.estimators[[M.estimator]]
  
  if (M.estimator == "least.abs.dev") {
    # least absolute deviation requires a different function to fit the model
    model <- rq(arr_delay ~ ., data = data)
  } else {
    model <- rlm(arr_delay ~ ., data = data, psi = M.phi)
  }
  
  MAD <- median(abs(model$residuals)) # median absolute deviation
  MADs[M.estimator] <- MAD
  
  MSE <- Metrics::mse(model$residuals, model$fitted.values)
  MSEs[M.estimator] <- MSE
  
  params <- summary(model)$coef
  M.estimator.underscores <- str_replace_all(M.estimator, "\\.", "_")
  write.csv(params, paste("coefficients/params_", M.estimator.underscores, "_1.csv", sep = ""))
  
  print(paste(M.estimator, "MAD:", MAD, sep = " "))
  print(paste(M.estimator, "MSE:", MSE, sep = " "))
  print(params)
}
write.csv(MADs, "MADs1.csv")
write.csv(MSEs, "MSEs1.csv")
```
Identify outliers based on least-squares model

```{r}
MADs <- numeric()
MSEs <- numeric()
for (M.estimator in names(M.estimators)) {
  M.phi <- M.estimators[[M.estimator]]
  
  if (M.estimator == "least.abs.dev") {
    # least absolute deviation requires a different function to fit the model
    model <- rq(arr_delay ~ ., data = data.no.outliers)
  } else {
    model <- rlm(arr_delay ~ ., data = data.no.outliers, psi = M.phi)
  }
  
  MAD <- median(abs(model$residuals)) # median absolute deviation
  MADs[M.estimator] <- MAD
  
  MSE <- Metrics::mse(model$residuals, model$fitted.values)
  MSEs[M.estimator] <- MSE
  
  params <- summary(model)$coef
  M.estimator.underscores <- str_replace_all(M.estimator, "\\.", "_")
  write.csv(params, paste("coefficients/params_", M.estimator.underscores, "_2.csv", sep = ""))
  
  print(paste(M.estimator, "MAD:", MAD, sep = " "))
  print(paste(M.estimator, "MSE:", MSE, sep = " "))
  print(params)
}
write.csv(MADs, "MADs2.csv")
write.csv(MSEs, "MSEs2.csv")
```

